### ISSUE TITLE
type conversion error

### ISSUE THREAD

**Issue by crazybits** [jcalfee/eosjc#4]
as quoted below, the `Missing checksum256$ in approve.fields.proposal_hash` was prompted while i use the latest system.msig contract to raise a proposal using eosjs@16.0.9, any idea?

> api < response 	 *******/get_abi {"account_name":"eosio.msig","abi":{"version":"eosio::abi/1.1","types":[],"structs":[{"name":"action","base":"","fields":[{"name":"account","type":"name"},{"name":"name","type":"name"},{"name":"authorization","type":"permission_level[]"},{"name":"data","type":"bytes"}]},{"name":"approval","base":"","fields":[{"name":"level","type":"permission_level"},{"name":"time","type":"time_point"}]},{"name":"approvals_info","base":"","fields":[{"name":"version","type":"uint8"},{"name":"proposal_name","type":"name"},{"name":"requested_approvals","type":"approval[]"},{"name":"provided_approvals","type":"approval[]"}]},{"name":"approve","base":"","fields":[{"name":"proposer","type":"name"},{"name":"proposal_name","type":"name"},{"name":"level","type":"permission_level"},{"name":"proposal_hash","type":"checksum256$"}]},{"name":"cancel","base":"","fields":[{"name":"proposer","type":"name"},{"name":"proposal_name","type":"name"},{"name":"canceler","type":"name"}]},{"name":"exec","base":"","fields":[{"name":"proposer","type":"name"},{"name":"proposal_name","type":"name"},{"name":"executer","type":"name"}]},{"name":"extension","base":"","fields":[{"name":"type","type":"uint16"},{"name":"data","type":"bytes"}]},{"name":"invalidate","base":"","fields":[{"name":"account","type":"name"}]},{"name":"invalidation","base":"","fields":[{"name":"account","type":"name"},{"name":"last_invalidation_time","type":"time_point"}]},{"name":"old_approvals_info","base":"","fields":[{"name":"proposal_name","type":"name"},{"name":"requested_approvals","type":"permission_level[]"},{"name":"provided_approvals","type":"permission_level[]"}]},{"name":"permission_level","base":"","fields":[{"name":"actor","type":"name"},{"name":"permission","type":"name"}]},{"name":"proposal","base":"","fields":[{"name":"proposal_name","type":"name"},{"name":"packed_transaction","type":"bytes"}]},{"name":"propose","base":"","fields":[{"name":"proposer","type":"name"},{"name":"proposal_name","type":"name"},{"name":"requested","type":"permission_level[]"},{"name":"trx","type":"transaction"}]},{"name":"transaction","base":"transaction_header","fields":[{"name":"context_free_actions","type":"action[]"},{"name":"actions","type":"action[]"},{"name":"transaction_extensions","type":"extension[]"}]},{"name":"transaction_header","base":"","fields":[{"name":"expiration","type":"time_point_sec"},{"name":"ref_block_num","type":"uint16"},{"name":"ref_block_prefix","type":"uint32"},{"name":"max_net_usage_words","type":"varuint32"},{"name":"max_cpu_usage_ms","type":"uint8"},{"name":"delay_sec","type":"varuint32"}]},{"name":"unapprove","base":"","fields":[{"name":"proposer","type":"name"},{"name":"proposal_name","type":"name"},{"name":"level","type":"permission_level"}]}],"actions":[{"name":"approve","type":"approve","ricardian_contract":""},{"name":"cancel","type":"cancel","ricardian_contract":""},{"name":"exec","type":"exec","ricardian_contract":""},{"name":"invalidate","type":"invalidate","ricardian_contract":""},{"name":"propose","type":"propose","ricardian_contract":""},{"name":"unapprove","type":"unapprove","ricardian_contract":""}],"tables":[{"name":"approvals","index_type":"i64","key_names":[],"key_types":[],"type":"old_approvals_info"},{"name":"approvals2","index_type":"i64","key_names":[],"key_types":[],"type":"approvals_info"},{"name":"invals","index_type":"i64","key_names":[],"key_types":[],"type":"invalidation"},{"name":"proposal","index_type":"i64","key_names":[],"key_types":[],"type":"proposal"}],"ricardian_clauses":[],"error_messages":[],"abi_extensions":[],"variants":[]}}
> 
> 
> 
> 5f295cda-3ffe-435a-8f31-14e7754c8da1:314616 error Error: [
>    ###  "Missing checksum256$ in approve.fields.proposal_hash"
> ]
error Error: [
    "Missing checksum256$ in approve.fields.proposal_hash"
]
    at module.exports (structs.js:142)
    at abi (abi-cache.js:63)
    at abi-cache.js:46
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:301
    at _callTimer (JSTimers.js:154)
    at _callImmediatesPass (JSTimers.js:202)
    at Object.callImmediates (JSTimers.js:470)
    at MessageQueue.__callImmediates (MessageQueue.js:329)
    at MessageQueue.js:147
>

**Comment by jcalfee** [comment]
Looks like that ABI has a new type in it `checksum256$`.  Have you already looked at eosjs@20?  It it easy to upgrade?

**Comment by crazybits** [comment]
there are too many breaking changes on eosjs@20, and re-write with type-script, should be no easy to upgrade, so i am still using your version

**Comment by jcalfee** [comment]
Where did you get eosio.msg ABI version 1.1?  In docker `eosio/eos:v1.5.2`, I see version `eosio::abi/1.0`.

Also: `> api < response 	 https://mainnet.eoscanada.com/v1/chain/get_abi {"account_name":"eosio.msig","abi":{"version":"eosio::abi/1.0"`

**Comment by crazybits** [comment]
try this : https://bostest.api.blockgo.vip, the issue seems like the eosjs@16.0.9 can not recognise the new type  `checksum256$`, the error is prompted from [source](https://github.com/EOSIO/eosjs/blob/v16.0.9/src/structs.js#L80)

**Comment by jcalfee** [comment]
Is there an example ABI 1.1 somewhere?  blockgo.vip is v1.0.2 .. I have check the latest eosio v1.6.0 but I don't see any ABI/1.1 examples.

**Comment by crazybits** [comment]
https://bos.api.blockgo.vip

```
{
	"account_name": "eosio.msig",
	"abi": {
		"version": "eosio::abi/1.1",
		"types": [],
		"structs": [{
			"name": "action",
			"base": "",
			"fields": [{
				"name": "account",
				"type": "name"
			}, {
				"name": "name",
				"type": "name"
			}, {
				"name": "authorization",
				"type": "permission_level[]"
			}, {
				"name": "data",
				"type": "bytes"
			}]
		}, {
			"name": "approval",
			"base": "",
			"fields": [{
				"name": "level",
				"type": "permission_level"
			}, {
				"name": "time",
				"type": "time_point"
			}]
		}, {
			"name": "approvals_info",
			"base": "",
			"fields": [{
				"name": "version",
				"type": "uint8"
			}, {
				"name": "proposal_name",
				"type": "name"
			}, {
				"name": "requested_approvals",
				"type": "approval[]"
			}, {
				"name": "provided_approvals",
				"type": "approval[]"
			}]
		}, {
			"name": "approve",
			"base": "",
			"fields": [{
				"name": "proposer",
				"type": "name"
			}, {
				"name": "proposal_name",
				"type": "name"
			}, {
				"name": "level",
				"type": "permission_level"
			}, {
				"name": "proposal_hash",
				"type": "checksum256$"
			}]
		}, {
			"name": "cancel",
			"base": "",
			"fields": [{
				"name": "proposer",
				"type": "name"
			}, {
				"name": "proposal_name",
				"type": "name"
			}, {
				"name": "canceler",
				"type": "name"
			}]
		}, {
			"name": "exec",
			"base": "",
			"fields": [{
				"name": "proposer",
				"type": "name"
			}, {
				"name": "proposal_name",
				"type": "name"
			}, {
				"name": "executer",
				"type": "name"
			}]
		}, {
			"name": "extension",
			"base": "",
			"fields": [{
				"name": "type",
				"type": "uint16"
			}, {
				"name": "data",
				"type": "bytes"
			}]
		}, {
			"name": "invalidate",
			"base": "",
			"fields": [{
				"name": "account",
				"type": "name"
			}]
		}, {
			"name": "invalidation",
			"base": "",
			"fields": [{
				"name": "account",
				"type": "name"
			}, {
				"name": "last_invalidation_time",
				"type": "time_point"
			}]
		}, {
			"name": "old_approvals_info",
			"base": "",
			"fields": [{
				"name": "proposal_name",
				"type": "name"
			}, {
				"name": "requested_approvals",
				"type": "permission_level[]"
			}, {
				"name": "provided_approvals",
				"type": "permission_level[]"
			}]
		}, {
			"name": "permission_level",
			"base": "",
			"fields": [{
				"name": "actor",
				"type": "name"
			}, {
				"name": "permission",
				"type": "name"
			}]
		}, {
			"name": "proposal",
			"base": "",
			"fields": [{
				"name": "proposal_name",
				"type": "name"
			}, {
				"name": "packed_transaction",
				"type": "bytes"
			}]
		}, {
			"name": "propose",
			"base": "",
			"fields": [{
				"name": "proposer",
				"type": "name"
			}, {
				"name": "proposal_name",
				"type": "name"
			}, {
				"name": "requested",
				"type": "permission_level[]"
			}, {
				"name": "trx",
				"type": "transaction"
			}]
		}, {
			"name": "transaction",
			"base": "transaction_header",
			"fields": [{
				"name": "context_free_actions",
				"type": "action[]"
			}, {
				"name": "actions",
				"type": "action[]"
			}, {
				"name": "transaction_extensions",
				"type": "extension[]"
			}]
		}, {
			"name": "transaction_header",
			"base": "",
			"fields": [{
				"name": "expiration",
				"type": "time_point_sec"
			}, {
				"name": "ref_block_num",
				"type": "uint16"
			}, {
				"name": "ref_block_prefix",
				"type": "uint32"
			}, {
				"name": "max_net_usage_words",
				"type": "varuint32"
			}, {
				"name": "max_cpu_usage_ms",
				"type": "uint8"
			}, {
				"name": "delay_sec",
				"type": "varuint32"
			}]
		}, {
			"name": "unapprove",
			"base": "",
			"fields": [{
				"name": "proposer",
				"type": "name"
			}, {
				"name": "proposal_name",
				"type": "name"
			}, {
				"name": "level",
				"type": "permission_level"
			}]
		}],
		"actions": [{
			"name": "approve",
			"type": "approve",
			"ricardian_contract": ""
		}, {
			"name": "cancel",
			"type": "cancel",
			"ricardian_contract": ""
		}, {
			"name": "exec",
			"type": "exec",
			"ricardian_contract": ""
		}, {
			"name": "invalidate",
			"type": "invalidate",
			"ricardian_contract": ""
		}, {
			"name": "propose",
			"type": "propose",
			"ricardian_contract": ""
		}, {
			"name": "unapprove",
			"type": "unapprove",
			"ricardian_contract": ""
		}],
		"tables": [{
			"name": "approvals",
			"index_type": "i64",
			"key_names": [],
			"key_types": [],
			"type": "old_approvals_info"
		}, {
			"name": "approvals2",
			"index_type": "i64",
			"key_names": [],
			"key_types": [],
			"type": "approvals_info"
		}, {
			"name": "invals",
			"index_type": "i64",
			"key_names": [],
			"key_types": [],
			"type": "invalidation"
		}, {
			"name": "proposal",
			"index_type": "i64",
			"key_names": [],
			"key_types": [],
			"type": "proposal"
		}],
		"ricardian_clauses": [],
		"error_messages": [],
		"abi_extensions": [],
		"variants": []
	}
}
```

**Comment by crazybits** [comment]
i try the add the type  ` "checksum256$": "fixed_bytes32",` in chain_types.json,  now i can raise proposal, but failed on proposal approve with folllowing error

 

> len validation requries a "length" property approve.proposal_hash action.data transaction.actions

**Comment by jcalfee** [comment]
Since $ is a binary extension, what should the json serialized data look like?  The type fixed_bytes32 serializes as hex in the json actions.  Can you see if it is hex or some other format?

**Comment by crazybits** [comment]
actually I also do not know what data format should be the new data type look like

**Comment by huanglei579** [comment]
we got abi 1.1 from BOS chain ,there is some different from eosio abi 1.0,like add structs.approve.fileds[3] ( ps: {name: "proposal_hash", type: "checksum256$"} ).
and I see eosio.contract update digest256 to checksum256 (https://github.com/EOSIO/eosio.contracts/commit/2b533f0e284f89013c8feb49b170d89fecbf7217),Is it that the eos contract has not been updated to the online?

**Comment by crazybits** [comment]
@jcalfee  looks the proposal_hash could be hex string of checksum256 or null, so i think we should create a a optional type to allow user keep it null for such param, but now the action params must all be filled if the abi is defined, otherwise if will failed, e.g the proposal_hash of approve action

**Comment by jcalfee** [comment]
Adding a question mark `checksum256?` should make it optional.

**Comment by crazybits** [comment]
I think it is fine to add ?  to indicate it is optional

**Comment by crazybits** [comment]
now i add ? for  the new type ,"checksum256$": "fixed_bytes32?",  it would prefill the 0 in the proposal_hash, but  signature can not pass the validation

> Error: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"Provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"wuychcvshbdx\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms, provided permissions [], provided keys [\"EOS7jvoEcb4vqgVBDiSjkD5nxULNmxnMarFCuxrPVzAGTv46PE3wh\"], and a delay max limit of 3888000000 ms","file":"authorization_manager.cpp","line_number":520,"method":"check_authorization"}]}}

```
{
  "compression": "none",
  "transaction": {
    "expiration": "2019-01-25T06:01:54",
    "ref_block_num": 25316,
    "ref_block_prefix": 3322318986,
    "max_net_usage_words": 0,
    "max_cpu_usage_ms": 0,
    "delay_sec": 0,
    "context_free_actions": [],
    "actions": [{
      "account": "eosio.msig",
      "name": "approve",
      "authorization": [{
        "actor": "wuychcvshbdx",
        "permission": "active"
      }],
      "data": {
        "proposer": "wuychcvshbdx",
        "proposal_name": "transfer24",
        "level": {
          "actor": "wuychcvshbdx",
          "permission": "active"
        },
        "proposal_hash": "0000000000000000000000000000000000000000000000000000000000000000"
      }
    }],
    "transaction_extensions": []
  },
  "signatures": ["SIG_K1_K2UkVUoxSe8Bi8NiBcfPohdQpxz1R3Hf2sTLHLoZ2e5Q6f41yEYPX2gd2b8nvaT8PjaXsYHjDf3BKxCiE7NXMRBeng1nT7"]
}
```

**Comment by jcalfee** [comment]
I'm not sure.. I'm really not setup to test this.  This is probably a new new type with its own serialization.

**Comment by crazybits** [comment]
@jcalfee any way to skip proposal_hash attribute  in tx Json input rather than pre-fill 0* if do not input value for this attribute

**Comment by jcalfee** [comment]
Omit it from the ABI will skip it entirely but of course that may make the signature invalid.

**Comment by yimapo** [comment]
I'm also blocked by this issue with eosjs@16.0.9.

**Comment by heipacker** [comment]
> I'm also blocked by this issue with eosjs@16.0.9.

+1

**Comment by crazybits** [comment]
issue workarounded,case closed

**Comment by jcalfee** [comment]
Looks like BOS may have a fix too: https://twitter.com/Boscore_BOS/status/1110077300022743040
